### ISSUE TITLE
using webpack to load htmlparser2 in browser

### ISSUE THREAD

**Issue by doberkofler** [fb55/htmlparser2#200]
I have been trying to use htmlparser2 in the browser using webpack but webpack complains about a missing loader for json files and I was wondering if and how this should actually work?

```
ERROR in ./~/entities/maps/entities.json
Module parse failed: D:\MyDev\ljs_app\trunk\periscope\examples\vendor\htmlparser2\node_modules\entities\maps\entities.json Unexpected token (1:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:9)
    at Parser.pp$4.raise (D:\MyDev\ljs_app\trunk\periscope\examples\vendor\htmlparser2\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (D:\MyDev\ljs_app\trunk\periscope\examples\vendor\htmlparser2\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (D:\MyDev\ljs_app\trunk\periscope\examples\vendor\htmlparser2\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (D:\MyDev\ljs_app\trunk\periscope\examples\vendor\htmlparser2\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (D:\MyDev\ljs_app\trunk\periscope\examples\vendor\htmlparser2\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseBlock (D:\MyDev\ljs_app\trunk\periscope\examples\vendor\htmlparser2\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$1.parseStatement (D:\MyDev\ljs_app\trunk\periscope\examples\vendor\htmlparser2\node_modules\acorn\dist\acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (D:\MyDev\ljs_app\trunk\periscope\examples\vendor\htmlparser2
...

```

**Comment by fb55** [comment]
You need the appropriate (JSON) loader. This will be included by default in webpack 2.

**Comment by doberkofler** [comment]
@fb55 I understand that i need the json-loader but how is need to be configured in webpack when I actually do not explicitly require a json file ?

**Comment by doberkofler** [comment]
@fb55 Should have tried before asking. A simple pre-loader seems to do the job:
```
preLoaders: [{test: /\.json$/, loader: 'json'}]
```
