### ISSUE TITLE
Error due to browser exclusion of readable-stream dependency

### ISSUE THREAD

**Issue by Mobe91** [fb55/htmlparser2#277]
When I install htmlparser2 via jspm and try to use it, I get the following error:

```
(SystemJS) Cannot read property 'prototype' of undefined
	TypeError: Cannot read property 'prototype' of undefined
	    at inherits (http://localhost:9000/jspm_packages/npm/inherits@2.0.1/inherits_browser.js:6:46)
	    at eval (http://localhost:9000/jspm_packages/npm/htmlparser2@3.10.1/lib/WritableStream.js:16:22)
	    at Object.eval (http://localhost:9000/jspm_packages/npm/htmlparser2@3.10.1/lib/WritableStream.js:23:3)
	    at eval (http://localhost:9000/jspm_packages/npm/htmlparser2@3.10.1/lib/WritableStream.js:25:4)
	    at eval (http://localhost:9000/jspm_packages/npm/htmlparser2@3.10.1/lib/WritableStream.js:26:3)
	    at eval (<anonymous>)
	    at Object.eval (http://localhost:9000/jspm_packages/npm/htmlparser2@3.10.1/lib/Stream.js:3:14)
	    at eval (http://localhost:9000/jspm_packages/npm/htmlparser2@3.10.1/lib/Stream.js:31:4)
	    at eval (http://localhost:9000/jspm_packages/npm/htmlparser2@3.10.1/lib/Stream.js:32:3)
	    at eval (<anonymous>)
	Evaluating http://localhost:9000/jspm_packages/npm/htmlparser2@3.10.1/lib/WritableStream.js
	Evaluating http://localhost:9000/jspm_packages/npm/htmlparser2@3.10.1/lib/Stream.js
```

The raw WriteableStream.js file looks like this:
```javascript
(function(System, SystemJS) {(function(require, exports, module, __filename, __dirname, global, GLOBAL) {/* */ 
(function(Buffer) {
  module.exports = Stream;
  var Parser = require('./Parser');
  var WritableStream = require('@empty').Writable;
  var StringDecoder = require('string_decoder').StringDecoder;
  var Buffer = require('buffer').Buffer;
  function Stream(cbs, options) {
    var parser = (this._parser = new Parser(cbs, options));
    var decoder = (this._decoder = new StringDecoder());
    WritableStream.call(this, {decodeStrings: false});
    this.once("finish", function() {
      parser.end(decoder.end());
    });
  }
  require('inherits')(Stream, WritableStream);
  Stream.prototype._write = function(chunk, encoding, cb) {
    if (chunk instanceof Buffer)
      chunk = this._decoder.write(chunk);
    this._parser.write(chunk);
    cb();
  };
})(require('buffer').Buffer);

}).apply(__cjsWrapper.exports, __cjsWrapper.args);
})(System, System);
```

The error happens on line `require('inherits')(Stream, WritableStream);` because `WritableStream` is undefined.
I guess the reason for this is that you have the following in your package.json:
```json
"browser": {
        "readable-stream": false
},
```
Thus ths `require('@empty')`.

I am using htmlparser2@3.10.1

**Comment by schadenn** [comment]
I've got a similar problem in my rollup build setup.

If I use rollup-plugin-resolve to use the pkg.browser field, it fails here:
```
var EVENTS = require("../").EVENTS;
```
